workflows:
  ios-build:
    name: iOS Build & TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: GameTaverns
    
    environment:
      node: 20
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: "com.gametaverns.app"
        APP_STORE_APP_ID: "6759586784"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gametaverns.app

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      cancel_previous_builds: true

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Patch Capacitor plugins
        script: |
          node scripts/patch-capacitor.cjs

      - name: Build web assets
        script: |
          npm run build -- --mode ios

      - name: Sync iOS platform
        script: |
          npx cap sync ios

      - name: Add entitlements
        script: |
          cat > ios/App/App/App.entitlements << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>aps-environment</key>
            <string>production</string>
            <key>com.apple.developer.associated-domains</key>
            <array>
              <string>applinks:hobby-shelf-spark.lovable.app</string>
            </array>
          </dict>
          </plist>
          EOF

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
      email:
        recipients:
          - tzolakis@gmail.com
        notify:
          success: true
          failure: true
