#!/bin/bash
#
# Setup Nginx reverse proxy with optional SSL via Certbot
# This script installs nginx and configures it to proxy to the GameHaven app
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}          ${BOLD}Nginx Reverse Proxy Setup${NC}                         ${CYAN}║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Load config if available
if [ -f .env ]; then
    # shellcheck disable=SC1091
    source .env
fi

# Prompt for domain
read -p "$(echo -e "${BLUE}?${NC} Enter your domain name (e.g., games.example.com): ")" DOMAIN

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Error: Domain is required${NC}"
    exit 1
fi

# Get app port
APP_PORT=${APP_PORT:-3000}
read -p "$(echo -e "${BLUE}?${NC} App port [${APP_PORT}]: ")" INPUT_PORT
APP_PORT=${INPUT_PORT:-$APP_PORT}

# Ask about SSL
read -p "$(echo -e "${BLUE}?${NC} Setup SSL with Let's Encrypt? (y/n) [y]: ")" SETUP_SSL
SETUP_SSL=${SETUP_SSL:-y}

# Detect package manager
if command -v apt-get &> /dev/null; then
    PKG_MGR="apt"
elif command -v dnf &> /dev/null; then
    PKG_MGR="dnf"
elif command -v yum &> /dev/null; then
    PKG_MGR="yum"
else
    echo -e "${RED}Error: Unsupported package manager. Please install nginx manually.${NC}"
    exit 1
fi

echo ""
echo -e "${BOLD}━━━ Installing Nginx ━━━${NC}"
echo ""

# Install nginx
if ! command -v nginx &> /dev/null; then
    echo -e "${CYAN}Installing nginx...${NC}"
    if [ "$PKG_MGR" = "apt" ]; then
        sudo apt-get update
        sudo apt-get install -y nginx
    elif [ "$PKG_MGR" = "dnf" ]; then
        sudo dnf install -y nginx
    else
        sudo yum install -y nginx
    fi
    echo -e "${GREEN}✓${NC} Nginx installed"
else
    echo -e "${GREEN}✓${NC} Nginx already installed"
fi

# Create nginx config
echo ""
echo -e "${BOLD}━━━ Configuring Nginx ━━━${NC}"
echo ""

NGINX_CONF="/etc/nginx/sites-available/gamehaven"
NGINX_ENABLED="/etc/nginx/sites-enabled/gamehaven"

# Check if sites-available exists (Debian/Ubuntu style)
if [ -d "/etc/nginx/sites-available" ]; then
    CONF_PATH="$NGINX_CONF"
    ENABLE_PATH="$NGINX_ENABLED"
else
    # RHEL/CentOS style
    CONF_PATH="/etc/nginx/conf.d/gamehaven.conf"
    ENABLE_PATH=""
fi

echo -e "${CYAN}Creating nginx configuration...${NC}"

sudo tee "$CONF_PATH" > /dev/null << NGINXCONF
# GameHaven Reverse Proxy Configuration
# Generated by setup-nginx.sh

server {
    listen 80;
    server_name ${DOMAIN};

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Logging
    access_log /var/log/nginx/gamehaven.access.log;
    error_log /var/log/nginx/gamehaven.error.log;

    # Main application
    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 86400;
    }

    # API Gateway (Kong)
    location /api/ {
        rewrite ^/api/(.*)\$ /\$1 break;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Studio: redirect /studio to /studio/ for consistency
    location = /studio {
        return 301 \$scheme://\$host/studio/;
    }

    # Studio (optional): served at https://<domain>/studio/
    # This avoids needing to expose a separate port over HTTPS.
    location /studio/ {
        rewrite ^/studio/(.*)\$ /\$1 break;
        proxy_pass http://127.0.0.1:${STUDIO_PORT:-3001};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }
}
NGINXCONF

echo -e "${GREEN}✓${NC} Nginx configuration created"

# Enable site (Debian/Ubuntu)
if [ -n "$ENABLE_PATH" ]; then
    sudo rm -f "$ENABLE_PATH"
    sudo ln -s "$CONF_PATH" "$ENABLE_PATH"
    
    # Disable default site if it exists
    if [ -f "/etc/nginx/sites-enabled/default" ]; then
        sudo rm -f "/etc/nginx/sites-enabled/default"
    fi
fi

# Test nginx configuration
echo -e "${CYAN}Testing nginx configuration...${NC}"
if sudo nginx -t; then
    echo -e "${GREEN}✓${NC} Nginx configuration valid"
else
    echo -e "${RED}Error: Invalid nginx configuration${NC}"
    exit 1
fi

# Restart nginx
echo -e "${CYAN}Restarting nginx...${NC}"
sudo systemctl restart nginx
sudo systemctl enable nginx
echo -e "${GREEN}✓${NC} Nginx restarted and enabled"

# Setup SSL with Certbot
if [[ "$SETUP_SSL" =~ ^[Yy] ]]; then
    echo ""
    echo -e "${BOLD}━━━ Setting Up SSL ━━━${NC}"
    echo ""
    
    # Install certbot
    if ! command -v certbot &> /dev/null; then
        echo -e "${CYAN}Installing certbot...${NC}"
        if [ "$PKG_MGR" = "apt" ]; then
            sudo apt-get install -y certbot python3-certbot-nginx
        elif [ "$PKG_MGR" = "dnf" ]; then
            sudo dnf install -y certbot python3-certbot-nginx
        else
            sudo yum install -y certbot python3-certbot-nginx
        fi
        echo -e "${GREEN}✓${NC} Certbot installed"
    else
        echo -e "${GREEN}✓${NC} Certbot already installed"
    fi
    
    # Get email for Let's Encrypt
    read -p "$(echo -e "${BLUE}?${NC} Email for Let's Encrypt notifications: ")" LE_EMAIL
    
    if [ -z "$LE_EMAIL" ]; then
        echo -e "${YELLOW}Skipping SSL setup - email required${NC}"
    else
        echo -e "${CYAN}Obtaining SSL certificate...${NC}"
        
        # Run certbot
        sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "$LE_EMAIL" --redirect
        
        echo -e "${GREEN}✓${NC} SSL certificate obtained and configured"
        
        # Patch SSL server block(s) to include /api and /studio location blocks.
        # IMPORTANT: Certbot may create/modify a separate *-le-ssl.conf file.
        # We patch ALL matching SSL vhost files for the domain to avoid the common
        # "return 404; # managed by Certbot" taking precedence.
        echo -e "${CYAN}Patching SSL configuration with proxy locations...${NC}"

        # Create a temporary string with the location blocks to inject
        INJECT_BLOCKS=$(cat << 'LOCATIONS'

    # API Gateway (Kong) - added by setup-nginx.sh
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Studio redirect - added by setup-nginx.sh
    location = /studio {
        return 301 $scheme://$host/studio/;
    }

    # Studio proxy - added by setup-nginx.sh
    location /studio/ {
        rewrite ^/studio/(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:STUDIO_PORT_PLACEHOLDER;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
    }
LOCATIONS
)
        # Replace placeholder with actual port
        INJECT_BLOCKS="${INJECT_BLOCKS//STUDIO_PORT_PLACEHOLDER/${STUDIO_PORT:-3001}}"

        patch_ssl_vhost_file() {
            local FILE="$1"
            if [ ! -f "$FILE" ]; then
                return 0
            fi

            # Remove Certbot's common catch-all 404 inside the SSL server block
            sudo sed -i '/return 404; # managed by Certbot/d' "$FILE"

            # Avoid duplicate injection
            if grep -q "# API Gateway (Kong) - added by setup-nginx.sh" "$FILE"; then
                echo -e "${GREEN}✓${NC} Proxy locations already present in: ${YELLOW}${FILE}${NC}"
                return 0
            fi

            sudo python3 << PYSCRIPT
import re

path = r"$FILE"

with open(path, "r", encoding="utf-8") as f:
    content = f.read()

# Only patch files that contain an SSL server block for the domain
if ("listen 443 ssl" not in content and "listen [::]:443 ssl" not in content):
    print(f"Skipping (no listen 443 ssl): {path}")
    raise SystemExit(0)

inject_text = '''$INJECT_BLOCKS'''

# Prefer inserting right after the main location / block if we can find it.
pattern = r'(location / \{[^}]+proxy_read_timeout 86400;\s*\})'
if re.search(pattern, content, flags=re.DOTALL):
    content = re.sub(pattern, r'\1' + inject_text, content, flags=re.DOTALL)
else:
    # Fallback: inject before the end of the first SSL server block
    # Find the first "server {" that has listen 443 and inject before its closing brace.
    m = re.search(r'(server\s*\{)(.*?)(\n\})', content, flags=re.DOTALL)
    if m and ("listen 443 ssl" in m.group(2) or "listen [::]:443 ssl" in m.group(2)):
        content = content[:m.end(2)] + inject_text + content[m.end(2):]
    else:
        # Last resort: inject before the final brace in the file
        last_brace = content.rfind('}')
        if last_brace > 0:
            content = content[:last_brace] + inject_text + "\n" + content[last_brace:]

with open(path, "w", encoding="utf-8") as f:
    f.write(content)

print(f"Injected proxy locations into: {path}")
PYSCRIPT

            echo -e "${GREEN}✓${NC} Patched: ${YELLOW}${FILE}${NC}"
        }

        # Patch the primary config path we created
        patch_ssl_vhost_file "$CONF_PATH" || true

        # Patch any Certbot-generated SSL vhost files for this domain
        # (commonly: /etc/nginx/sites-enabled/<name>-le-ssl.conf)
        SSL_CANDIDATES=$(sudo grep -RIl "server_name\s\+${DOMAIN};" /etc/nginx 2>/dev/null | head -n 50 || true)
        while IFS= read -r f; do
            # Only patch candidates that look like vhost config files
            case "$f" in
                *.conf|*/sites-available/*|*/sites-enabled/*)
                    patch_ssl_vhost_file "$f" || true
                    ;;
            esac
        done <<< "$SSL_CANDIDATES"

        # Test and reload nginx
        if sudo nginx -t; then
            sudo systemctl reload nginx
            echo -e "${GREEN}✓${NC} Nginx reloaded with updated SSL configuration"
        else
            echo -e "${RED}Warning: Nginx config test failed after patching. Please check manually.${NC}"
        fi
        
        # Setup auto-renewal
        echo -e "${CYAN}Setting up auto-renewal...${NC}"
        (sudo crontab -l 2>/dev/null; echo "0 12 * * * /usr/bin/certbot renew --quiet") | sudo crontab -
        echo -e "${GREEN}✓${NC} Auto-renewal configured"
    fi
fi

# Update .env with new URLs if SSL was set up
if [[ "$SETUP_SSL" =~ ^[Yy] ]] && [ -n "$LE_EMAIL" ]; then
    echo ""
    echo -e "${CYAN}Updating configuration with HTTPS URLs...${NC}"
    
        # Update SITE_URL and API_EXTERNAL_URL in .env
    if [ -f .env ]; then
        sed -i "s|^SITE_URL=.*|SITE_URL=\"https://${DOMAIN}\"|" .env
        sed -i "s|^API_EXTERNAL_URL=.*|API_EXTERNAL_URL=\"https://${DOMAIN}/api\"|" .env
        echo -e "${GREEN}✓${NC} Updated .env with HTTPS URLs"
        
        echo -e "${CYAN}Restarting containers with new config...${NC}"
        docker compose down
        docker compose up -d
        echo -e "${GREEN}✓${NC} Containers restarted"
    fi
fi

# Print summary
echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}             ${BOLD}${GREEN}Nginx Setup Complete!${NC}                         ${CYAN}║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

if [[ "$SETUP_SSL" =~ ^[Yy] ]] && [ -n "$LE_EMAIL" ]; then
    echo -e "  ${BOLD}Your site is available at:${NC}      ${GREEN}https://${DOMAIN}${NC}"
    echo -e "  ${BOLD}Supabase Studio:${NC}                ${GREEN}https://${DOMAIN}/studio/${NC}"
else
    echo -e "  ${BOLD}Your site is available at:${NC}      ${GREEN}http://${DOMAIN}${NC}"
    echo -e "  ${BOLD}Supabase Studio:${NC}                ${GREEN}http://${DOMAIN}/studio/${NC}"
fi

echo ""
echo -e "${BOLD}Useful Commands:${NC}"
echo -e "  Test nginx:     ${YELLOW}sudo nginx -t${NC}"
echo -e "  Reload nginx:   ${YELLOW}sudo systemctl reload nginx${NC}"
echo -e "  View logs:      ${YELLOW}sudo tail -f /var/log/nginx/gamehaven.*.log${NC}"
echo -e "  Renew SSL:      ${YELLOW}sudo certbot renew${NC}"
echo ""
